---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cogiwggd/public_html/
    - export NODE_ENV=production
    - source ~/.bashrc
    - cd $DEPLOYMENT_SOURCE
    - npm install
    - npm run build
    - rm -rf $DEPLOYPATH/*
    - cp -r dist/* $DEPLOYPATH/